name: Test
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: build the docker image
        run: docker build -t liatro_latest .  
      - name: launch the docker image 
        run: docker run --net host -d -p 80:80  liatro_latest
      # - name: run tests
      #   uses: liatrio/github-actions/apprentice-action@master
      - name: Login to Docker Hub 
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password:  ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: prestonmblake/liatro:latest, prestonmblake/liatro:${{github.run_number}}


      # run: docker run -d -p 3000:3000 --name node-app liatro 




  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: run tests
  #     uses: liatrio/github-actions/apprentice-action@master
  