name: Test
on:
  push:
    braches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: build the docker image
        run: docker buit -t liatro .  
      # - name: launch the docker image 
      # run: docker run -d -p 3000:3000 --name node-app liatro 




  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: run tests
  #     uses: liatrio/github-actions/apprentice-action@master
  